### ISSUE TITLE
Upload asset error

### ISSUE THREAD

**Issue by Slgoetz** [riasvdv/craft-scout#104]
After updating Craft-Scout we tried to upload an image an received the error of
```Upload failed. The error message was: “Return value of rias\scout\behaviors\SearchableBehavior::getRelatedElements() must be an instance of Tightenco\Collect\Support\Collection, instance of Illuminate\Support\Collection returned”```

Can provide more details - just let me know what is needed.

**Comment by riasvdv** [comment]
Fixed in 2.0.2!
