### ISSUE TITLE
No Errors, no recors in index

### ISSUE THREAD

**Issue by Lennso** [riasvdv/craft-scout#107]
I am using Craft in local setup with mamp. At first everything worked fine and my entries were pushed to algolia index. but since a few days nothing happens. i tried everything (reading logs, looking for api errors, changing the section, disable fields) but i cant get it to work :-(

if i save an entry there is no error.

my scout.php
`<?php

return [
	'sync' => true,
	'connect_timeout' => 1,
	'application_id' => 'XYZ',
	'admin_api_key' => 'XYZ',
	'search_api_key' => 'XYZ', // optional
	'mappings' => [
		[
			'indexName' => 'pluswert-guide',
			'indexSettings' => [
				'settings' => [
				],
				'forwardToReplicas' => 'true',
			],
			'elementType' => \craft\elements\Entry::class,
			'criteria' => [
				'section' => 'guideArticle',
				'siteId' => 4
			],
			'transformer' => function(craft\elements\Entry $entry) {

				$date = date_format($entry->dateUpdated, 'd.m.Y \u\m H:i');

				$categories = array_map(function($el) {
					return [
						'title' => $el->title,
						'id' => $el->id
					];
				}, $entry->guideKategorie->all());

				$products = array_map(function($el) {
					return [
						'title' => $el->title,
						'id' => $el->id
					];
				}, $entry->produktart->all());

				$tags = array_map(function($el) {
					return [
						'title' => $el->title,
						'id' => $el->id
					];
				}, $entry->tags->all());

				$insurance = array_map(function($el) {

					$logo = null;
					if(!empty($el->logo->one())) {
						$logo = $el->logo[0]->url;
					}

					return [
						'title' => $el->title,
						'id' => $el->id,
						'logo' => $logo,
					];
				}, $entry->gesellschaft->all());

				$files = array_map(function($el) {
					return [
						'title' => $el->title,
						'id' => $el->id,
						'url' => $el->url
					];
				}, $entry->guideFiles->all());

				return [
					'status' => $entry->status,
					'publish' => $entry->public,
					'title' => $entry->title,
					'url' => $entry->url,
					'dateUpdated' => $date,
					'id' => $entry->id,
					'description' => strip_tags($entry->description),
					'category' => $categories,
					'product' => $products,
					'insurance' => $insurance,
					'tags' => $tags,
					'source' => $entry->quelle,
					'files' => $files,
				];
			},
		],
	],
];`
queue.log is attached
[queue.log](https://github.com/riasvdv/craft-scout/files/3661598/queue.log)

thanks 4 yout help!

**Comment by riasvdv** [comment]
You’re still using the v1 configuration, please make sure to update Scout to v2 and follow the new configuration, that should solve your issues

**Comment by Lennso** [comment]
> You’re still using the v1 configuration, please make sure to update Scout to v2 and follow the new configuration, that should solve your issues

You saved my weekend! My fault, sorry!!
