### ISSUE TITLE
How to setup scout.php config for multi-environment?

### ISSUE THREAD

**Issue by icreatestuff** [riasvdv/craft-scout#108]
I'd like to apply different config settings based on the environment (local/development, staging, production etc). Simple things initially like turning off syncing entirely in the development environment.

I thought something like this might work
```
<?php

use craft\helpers\UrlHelper;

return [
    'sync' => getenv('SCOUT_SYNC'),
    _...more config here_
```

and then have  `SCOUT_SYNC=false` in my .env file but I don't think that's working? 

Is there a way to achieve this?
Thanks

**Comment by besimhu** [comment]
I would like to know if this is possible too. Especially being able to use a different index name if I am on dev vs live for example.

**Comment by riasvdv** [comment]
You'll want to use `getenv('SCOUT_SYNC') === 'true'`, because `getenv()` always returns a string for some reason

**Comment by jamesmacwhite** [comment]
In addition, you could also do this:

```
// filter_var
filter_var(getenv('SCOUT_SYNC'), FILTER_VALIDATE_BOOLEAN)

// Casting getenv
(bool) getenv('SCOUT_SYNC')
```

true/false or 0/1 would return a boolean in both examples.

**Comment by besimhu** [comment]
I should have responded to this. I was able to setup several ENV keys:

1. `'indexName' => getenv('ALGOLIA_INDEX_ENTRIES'),`
2. `'sync' => getenv('ENVIRONMENT') === 'production' ? true : false,`

^ my current setup, I probably could have also made the sync a custom env variable. But for now I am fine just syncing on production.
