### ISSUE TITLE
Generate image/thumb, in cli mode don't work

### ISSUE THREAD

**Issue by mustasj** [riasvdv/craft-scout#109]
I have problem with the batch processing, or cli method. When i save the entry one at the time it generates a thumb, but in batch mode it is always `null`.

This is the code for it:
```php
$thumb = null;
$picture = $entry->ansattbilde[0] ?? null;
if ($picture) {
    $pictureUrl = $picture->getUrl( ["height" => 136, "width" => 136, "mode" => "crop", "format" => 'jpg'] ) ?? null;
    if ($pictureUrl && strpos( $pictureUrl, 'not-found' ) === false) {
        $thumb = Craft::getAlias( '@baseUrl' ) . str_replace( Craft::getAlias( '@baseUrl' ), "", $pictureUrl );
    }
}
```
I have added a failsafe of an image for some reason is not found.

I have also added settings for Imager and generateTransform at the top of the transformer, so they generate on request:
```php
Imager::$plugin->setSettings( ['useForNativeTransforms' => false] );
Craft::$app->config->general->generateTransformsBeforePageLoad = true;
```
and this is the query:
```php
->criteria( function(EntryQuery $query) {
    return $query->site( 'nb_konsern' )->section( ['ansatt', 'ansattManuellOppforing'] )->with( ['ansattbilde'] );
} )
```
I have also tried it with `'queue'` `true` and `false`
Any idea of why that shouldn't work on batch?

**Comment by riasvdv** [comment]
When you save the entry, the image is probably eager loaded into your entry, when it's batched, it isn't, so you want to do the following:

```php
$picture = $entry->ansattbilde[0] ?? $entry->ansattbilde->one();
```

That should work

**Comment by mustasj** [comment]
Well it almost worked, i had to add a check to see if php was run in CLI mode, and make two queries, with and without eager loading.
Is it a reason why we cant use eager loading in the batch?

**Comment by riasvdv** [comment]
The batch runs a different query to make the indexing faster
