### ISSUE TITLE
getRelatedElements fills up the memory

### ISSUE THREAD

**Issue by mustasj** [riasvdv/craft-scout#112]
I have 9 sites in one Craft with a ton of content, users, images, products, variants, matrix block etc.
When i try to save an entry the `getRelatedElements()` just collects so much that the memory cant handle the load.
Should that prosess instead make a job to handles all of this logic? as of now i cant use the plugin because it just chokes the system.

**Comment by timkelty** [comment]
@mustasj running into the same problem. I believe you're right, we need to offload this to the queue.
