### ISSUE TITLE
Records not synced when post date is scheduled in the future

### ISSUE THREAD

**Issue by kevinarrieta** [riasvdv/craft-scout#113]
Hello, I have some entries which are scheduled to be published in the future, when they get published the records are not synced (also noticed the same with ajax entry updates), so you know if this behavior is supported? 

Any hints for a workaround is also appreciated it.

**Comment by riasvdv** [comment]
Craft does not emit events when an entry is published, so there is no way for Scout to actually sync it at publishing time, what you can do is one of two things:

1. Sync everything by using the criteria, then filter when you query Algolia
2. Use something like https://github.com/sjelfull/craft3-publishedevent to trigger a published event and re-save the entry to have Scout pick it up and sync to Algolia

**Comment by kevinarrieta** [comment]
Thanks for clarifying! Very helpful!

**Comment by lenvanessen** [comment]
@riasvdv I'd like to revisit this topic. There are certainly ways we could solve this from scout. One of them being creating a separate table and storing the element publishing dates like the Blitz plugin does. 

Could this be on the roadmap for Scout, would be very helpfull.

**Comment by lenvanessen** [comment]
@riasvdv and maybe we can add a config option to specify custom events that Scout wil listen to for updating the article, making the process more lightweight and straightforward than forcing a resave.
