### ISSUE TITLE
Disabled elements removed from index?

### ISSUE THREAD

**Issue by engram-design** [riasvdv/craft-scout#125]
More of a question than an issue, but from what I can tell in my testing disabled elements aren't removed from Algolia. We have a multi-site setup, where each site's entry is an individual record on Algolia. What seems to be happening is that when a site's entry is disabled, its not being removed from the index.

Does this sounds right? Should I maybe be doing something different like pushing all entries, regardless of status to Algolia, adding the status to the index data, and then filtering based on that value?

Just wanted to check expected behaviour.

**Comment by riasvdv** [comment]
If an entry no longer validates the criteria it should be removed from the index, is there any more info you can give me like the Scout config and criteria?

**Comment by engram-design** [comment]
Ah, looks like this is because I'm modifying `objectID` in the transformer.

```
return [
    'objectID' => $element->id . '_' . $element->siteId,
    'title' => $element->title,
    'id' => $element->id,
    'url' => $element->url,
    'uri' => $element->uri,
    'siteId' => $element->siteId,
];
```

This is because I want a separate item in Algolia for each site. Stepping through the code, its failing to find the object to delete, because the object ID is incorrect (its trying to delete an object of `12456`, but its stored as `123456_1`).

Maybe I'm going about it the wrong way?

**Comment by riasvdv** [comment]
You shouldn’t have to touch the ObjectID, Scout makes sure they’re unique across different sites

**Comment by engram-design** [comment]
@riasvdv Not seeing that behaviour. Its adding an item with an objectID of `296315`, when I save an item on one site, then saving the same entry on another site overwrites the same item.

For example, see this in Aloglia after saving an entry in one site (siteID 2) 
 - https://d.pr/free/i/NsTk4P, and then saving the same entry in siteID 3 - https://d.pr/free/i/KE1tDJ, which has overwritten the object in Algolia.

**Comment by riasvdv** [comment]
Ah right, for Scout v2 I stepped away from that because it was never possible to track all the elements correctly across different sites.

If you want separate entries for different sites, you should create separate indices, and use Algolia to search across them https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/?language=javascript

**Comment by engram-design** [comment]
Gotcha, I'll see what I can do, just requires a bit more re-jigging on the front-end.

FWIW, its a matter of changing `https://github.com/riasvdv/craft-scout/blob/master/src/engines/AlgoliaEngine.php#L60`. I would've thought changing to `return $object['objectID']` would do the trick, but `$object` is an Entry element...

**Comment by engram-design** [comment]
Anyway, will go for the multi-indices option, thanks!
