### ISSUE TITLE
Installation Error: Class 'Tightenco\Collect\Support\Collection' not found

### ISSUE THREAD

**Issue by johnj24** [riasvdv/craft-scout#126]
Hello,

I've tried installing Scout locally a couple of times and am getting the same error each time. I've searched around and haven't found anything regarding this error for Craft. Any ideas?

```
Scout has been added, but an error occurred when installing it.

Error: Class 'Tightenco\Collect\Support\Collection' not found 
```

Craft: 3.3.17

**Comment by riasvdv** [comment]
Can you try running a `composer update` and see if that fixes the issue?

**Comment by Josh-Mus** [comment]
@johnj24 did you find a fix for this in the end?

**Comment by johnj24** [comment]
I'm sure there's a better way than what I did, but I ended up reinstalling Craft and my other plugins. Scout installed just fine after that.
