### ISSUE TITLE
shouldBeSearchable is always false

### ISSUE THREAD

**Issue by joshuabaker** [riasvdv/craft-scout#134]
When saving entries in one of our sites `shouldBeSearchable` is returning `false` for every element.

**Comment by joshuabaker** [comment]
Some initial debugging suggests that every call from [`L164`](https://github.com/riasvdv/craft-scout/blob/3a89a0383bc0e249e4c6c27e6124044d64f15a0a/src/behaviors/SearchableBehavior.php#L163) is returning `true` for `getIsRevision`, even for new entries.

**Comment by riasvdv** [comment]
When you save an entry, it always first saves a revision and afterwards saves a full entry, if you're debugging using something like dump & die, only the first save will be logged.

Are you sure it's **always** returning true?

**Comment by joshuabaker** [comment]
You’re right, @riasvdv. I was using dumb and die. The second call does look indeed look correct.

Nothing is getting indexed in one of our installs. If I dump out the raw SQL there’s a difference between what goes in via [`criteria`](https://github.com/riasvdv/craft-scout/blob/3a89a0383bc0e249e4c6c27e6124044d64f15a0a/src/ScoutIndex.php#L66) and what comes out [`validatesCriteria`](https://github.com/riasvdv/craft-scout/blob/3a89a0383bc0e249e4c6c27e6124044d64f15a0a/src/behaviors/SearchableBehavior.php#L38). Do you have any idea on why this might happen? Perhaps something internal?

**Comment by riasvdv** [comment]
Can you share your scout config file, how you configured the criteria & index?

**Comment by joshuabaker** [comment]
I’ve paired it back a lot. Here’s what I’m currently using.

```php
<?php

use craft\elements\db\EntryQuery;
use rias\scout\IndexSettings;
use rias\scout\ScoutIndex;
use search\transformers\PersonTransformer;

return [
    'application_id' => getenv('ALGOLIA_APP_ID'),
    'admin_api_key' => getenv('ALGOLIA_API_KEY'),

    'indices' => [
        ScoutIndex::create(getenv('ALGOLIA_INDEX_PREFIX') . 'people')
            ->criteria(function (EntryQuery $query) {
                return $query->section('people');
            })
            ->transformer(PersonTransformer::class)
            ->indexSettings(
                IndexSettings::create()
            )
    ],
];
```

**Comment by riasvdv** [comment]
>  If I dump out the raw SQL there’s a difference between what goes in via criteria and what comes out validatesCriteria. 

What's the difference there? It should only be adding an extra constraint on the id of the entry

**Comment by joshuabaker** [comment]
<details>
<summary>Before</summary>
SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`enabled` AS `enabledForSite`, `elements_sites`.`uri`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_consentAcceptButtonText`, `content`.`field_locationAddress`, `content`.`field_attachmentDate`, `content`.`field_attachmentDescription`, `content`.`field_locationEmail`, `content`.`field_personFacebookProfileId`, `content`.`field_personFirstName`, `content`.`field_locationGeolocation`, `content`.`field_footerHeadOfficeText`, `content`.`field_imageVariants`, `content`.`field_personInstagramHandle`, `content`.`field_personJobTitle`, `content`.`field_personLastName`, `content`.`field_personLinkedinUrl`, `content`.`field_locationMapUrl`, `content`.`field_locationBusRoutes`, `content`.`field_locationRailStations`, `content`.`field_locationTubeStations`, `content`.`field_locationOpeningHours`, `content`.`field_postImageOptimized`, `content`.`field_personOtherExperience`, `content`.`field_personImageVariants`, `content`.`field_personPostNominals`, `content`.`field_seoSettings`, `content`.`field_eventSummary`, `content`.`field_locationTelephone`, `content`.`field_clinicText`, `content`.`field_consentText`, `content`.`field_contentText`, `content`.`field_eventText`, `content`.`field_eventTicketUrl`, `content`.`field_personTitle`, `content`.`field_personTwitterHandle`, `content`.`field_personWebsiteUrl`, `content`.`field_widescreenImageVariants`, `content`.`field_personWorkExperience`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId` FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId` FROM `elements` `elements` INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`) LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT * FROM `structures` WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL))) WHERE (`elements_sites`.`siteId`='1') AND (`elements`.`id`=28748) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2020-01-13 13:34:19') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2020-01-13 13:34:19'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC) `subquery` INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId` INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId` LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC
</details>

<details>
<summary>After</summary>
SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`enabled` AS `enabledForSite`, `elements_sites`.`uri`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_consentAcceptButtonText`, `content`.`field_locationAddress`, `content`.`field_attachmentDate`, `content`.`field_attachmentDescription`, `content`.`field_locationEmail`, `content`.`field_personFacebookProfileId`, `content`.`field_personFirstName`, `content`.`field_locationGeolocation`, `content`.`field_footerHeadOfficeText`, `content`.`field_imageVariants`, `content`.`field_personInstagramHandle`, `content`.`field_personJobTitle`, `content`.`field_personLastName`, `content`.`field_personLinkedinUrl`, `content`.`field_locationMapUrl`, `content`.`field_locationBusRoutes`, `content`.`field_locationRailStations`, `content`.`field_locationTubeStations`, `content`.`field_locationOpeningHours`, `content`.`field_postImageOptimized`, `content`.`field_personOtherExperience`, `content`.`field_personImageVariants`, `content`.`field_personPostNominals`, `content`.`field_seoSettings`, `content`.`field_eventSummary`, `content`.`field_locationTelephone`, `content`.`field_clinicText`, `content`.`field_consentText`, `content`.`field_contentText`, `content`.`field_eventText`, `content`.`field_eventTicketUrl`, `content`.`field_personTitle`, `content`.`field_personTwitterHandle`, `content`.`field_personWebsiteUrl`, `content`.`field_widescreenImageVariants`, `content`.`field_personWorkExperience`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId` FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId` FROM `elements` `elements` INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`) LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT * FROM `structures` WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL))) WHERE (`entries`.`sectionId`='4') AND (`elements_sites`.`siteId`='1') AND (`elements`.`id`=28748) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2020-01-13 13:30:00') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2020-01-13 13:30:00'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`id` IN (SELECT `targets1`.`sourceId` FROM `relations` `targets1` WHERE `targets1`.`targetId`='28748')) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC) `subquery` INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId` INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId` LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC
</details>

**Comment by riasvdv** [comment]
That `after` one looks like this call https://github.com/riasvdv/craft-scout/blob/master/src/behaviors/SearchableBehavior.php#L121

**Comment by joshuabaker** [comment]
That makes sense, however, I’m only outputting the raw SQL if the owner ID matches.

```php
if ($this->owner->id == 28748) {
    exit($criteria->id($this->owner->id)->getRawSql());
}
```

**Comment by riasvdv** [comment]
Do you have queue enabled for Scout?

**Comment by joshuabaker** [comment]
I’ve disabled it locally.

**Comment by riasvdv** [comment]
Then it will do the related query first, and then index the element

https://github.com/riasvdv/craft-scout/blob/3a89a0383bc0e249e4c6c27e6124044d64f15a0a/src/behaviors/SearchableBehavior.php#L88-L92

That's just the way the code is structured and shouldn't cause any issues

**Comment by joshuabaker** [comment]
It should get there though as `validatesCriteria` returns `false`.

https://github.com/riasvdv/craft-scout/blob/3a89a0383bc0e249e4c6c27e6124044d64f15a0a/src/behaviors/SearchableBehavior.php#L75-L77

**Comment by riasvdv** [comment]
Right, can you try logging the validatesCriteria output and save the entry? Want to see how many times it gets called and the result each time for that entry.

There's nothing extraordinary about the entry right? It's enabled in every site?

**Comment by joshuabaker** [comment]
It got called 3 times.

```
2020-01-13 14:08:30 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] Called
2020-01-13 14:08:30 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] Called
2020-01-13 14:08:30 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] Called
```

**Comment by riasvdv** [comment]
And the result is `false` every time?

**Comment by joshuabaker** [comment]
Sorry, yes, it’s `false` every time.

```
2020-01-13 14:10:32 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] false
2020-01-13 14:10:32 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] false
2020-01-13 14:10:32 [-][1][-][info][rias\scout\behaviors\SearchableBehavior::validatesCriteria] false
```

**Comment by joshuabaker** [comment]
And, no, nothing extraordinary. One site. One entry. Definitely enabled.

**Comment by joshuabaker** [comment]
I’ve found it. Rather embarrassing. It’s [this code](https://github.com/riasvdv/craft-scout/issues/132#issue-545844395).

The `$index->criteria` call isn’t cloned so is instead modified. It explains the `targetElement` adjustment to the query.

**Comment by riasvdv** [comment]
Ah! Yeah the clone is pretty important, glad you found it

**Comment by joshuabaker** [comment]
Just reinstated everything and it’s working again. Thanks so much for your time, @riasvdv. 🍻
