### ISSUE TITLE
Toggle in settings to stop validating project config

### ISSUE THREAD

**Issue by martinhellwagner** [riasvdv/craft-scout#156]
@riasvdv 

Since our use of Scout is somewhat complicated and we end up having three arrays with the same `indexName` in our `indices` in the Scout config, the exception "Index names must be unique in the Scout config" is thrown. However, there is unfortunately no way around creating non-unique index names with our current configuration, and the indices get pushed to Algolia correctly.

Might it be possible to add a toggle in the settings to disable config validation – or maybe even just in the `scout.php` config file? It would help us tremendously. 🙏 

Thanks in advance!

**Comment by timkelty** [comment]
@martinhellwagner could you post your scout config?

**Comment by martinhellwagner** [comment]
```
<?php

$mapper = include '_partials/scout/mapper.php';
$mappingsFolder = __DIR__ . '/_partials/scout/mappings/';
$mappingsFiles = scandir($mappingsFolder);
$mappingsList = [];
$finalMappings = [];

foreach ($mappingsFiles as $file) {
    if (in_array($file, ['.', '..'])) continue;
    $indexName = basename($file, '.php') . '_' . \Craft::$app->config->env;
    $mappingsList[$indexName] = include $mappingsFolder . $file;
}

foreach ($mappingsList as $indexName => $mappings) {
    foreach ($mappings as $section => $mapping) {
        $finalMappings[] = $mapper($mapping, $section, $indexName)[0];
    }
}

$result = [
    "sync" => false,
    "connect_timeout" => 1,
    "application_id" => "xxx",
    "admin_api_key" => "xxx",
    "indices" => $finalMappings,
];

return $result;
```

**Comment by martinhellwagner** [comment]
We have a pretty complicated mapping going on that _needs_ to be run three times (one for each section) for a specific index name.

**Comment by timkelty** [comment]
I know this isn't the answer you want – but until I can take a look, it seems like you could have one index, with the element querying for all three sections, and then deal with any indexing differences in the  transformer.

The only way I can imagine needing to do what you're describing is if you needed a given entry to be mapped to 3 unique Algolia objects in the same Algolia index.

**Comment by martinhellwagner** [comment]
This is actually what I've tried, but couldn't get it to work. Unfortunately I can't spend any more time on that right now, as we need indexing to work again sooner than later.

**Comment by timkelty** [comment]
@martinhellwagner fair enough – there's been discussion of making indexName non-unique here: https://github.com/riasvdv/craft-scout/issues/69

I'm hoping to get to that this week, which hopefully should help you. Stay tuned!

**Comment by martinhellwagner** [comment]
Thank you so much – really appreciated! 👍 

By the way, I'm also experiencing the problem described in https://github.com/riasvdv/craft-scout/issues/152 – just FYI.

**Comment by timkelty** [comment]
Thanks - hoping to plow through a bunch of issues this week.

**Comment by timkelty** [comment]
@martinhellwagner Going to close this in favor of a solution from #69.
