### ISSUE TITLE
Not unique index names

### ISSUE THREAD

**Issue by NancyLussier** [riasvdv/craft-scout#168]
I think this should be optional (a config parameter). I need to index entries and products in one single index and I can't with the unique index names validation : https://github.com/riasvdv/craft-scout/blob/e36d5c7cdcc3380d1de53fc818e77b182ebf9976/src/Scout.php#L135

**Comment by NancyLussier** [comment]
I saw there is already an issue opened for this.

**Comment by timkelty** [comment]
👍 hope to get some time in the coming weeks
