### ISSUE TITLE
Run commands from CMS

### ISSUE THREAD

**Issue by Moorst** [riasvdv/craft-scout#42]
I've disabled sync and set up cron jobs to run every morning to prevent too many operations running and using up all the quota. It would be useful for permitted CMS users to have a button to refresh the index manually, e.g. if they push a new event that they want to be immediately searchable on the day.

Is this something that's in the pipeline?

**Comment by Rias500** [comment]
Not currently, will gladly accept a PR for it though. I tend to not add features that I don't need myself.

**Comment by nicgordon** [comment]
I have opened the PR referenced above to address this issue. Please let me know if you have any feedback.

**Comment by riasvdv** [comment]
v2 is ready for testing: https://github.com/riasvdv/craft-scout/tree/v2 which includes a Utility to manage indices
