### ISSUE TITLE
scout/index/import only works for default site

### ISSUE THREAD

**Issue by timkelty** [riasvdv/craft-scout#54]
With multiple sites, when you run `scout/index/import`, it will only index as the default site.

On the other hand – when you save an entry, it will index the element for every site that element is enabled in.

Seems like the behavior should be consistent.

NOTE: this only applies if your criteria does not specify `site`/`siteId` explicitly. Unfortunately, those params cannot (yet) accept arrays or `null`. The way I've worked around it is to have an explicit scout mapping for each site, with the only thing being different is the `siteId` param of the criteria.

**Comment by riasvdv** [comment]
Should be able to implement a parameter for the import command that takes a `siteId`. If no parameter is passed it should do every site, the same way it happens on save

**Comment by timkelty** [comment]
@riasvdv now that `site`/`siteId` can accept `*` (https://github.com/craftcms/cms/issues/2854), this is less of an annoyance.

However, it may make sense to _default_ `site` to `*`. That way if `site` or `siteId` is explicitly passed, it should take those values, otherwise it will work on all sites.

**Comment by smaida** [comment]
@riasvdv Thoughts on implementing this? It looks like a modification to canIndexElement and canDeindexElement in AlgoliaIndex.php would allow multiple sites to push to a single index. Also, while looking at this, is it accurate that canDeindexElement only supports siteId and not site? 

```
$site = (isset($this->criteria['site'])) ? (array) $this->criteria['site'] : null;

if (isset($site) && !in_array($element->site->handle, $site)) {
        return false;
}
```

**Comment by riasvdv** [comment]
The whole site / siteId implementation has gone through a lot of changes trying to get the indexing "correct" with multiple sites & locales, to be really honest I have no idea what the correct solution would be.

Certainly not right now with Craft 3.2 and 3.3

People are also using Scout with way bigger indexes and mappings than I have foreseen, and it's getting a bit overwhelming with all the different configurations, as I personally only use it on a site with 1 site, 1 locale, and about 1000 entries 😅

**Comment by riasvdv** [comment]
That said, I'm thinking of creating a big breaking release, that rethinks some concepts of Scout and its configuration to make it all more in line with what you'd expect to happen when you configure it in certain ways, but I can't promise any ETA

**Comment by riasvdv** [comment]
In v2, every ScoutIndex (used to be called mapping) is only for 1 siteId, which solves all these issues

**Comment by smaida** [comment]
@riasvdv In v2, can we push multiple sites into the same index using multiple ScoutIndex configurations? We do a ton of Algolia work and IMO that I would expect that to be a common need for unified search UIs where we're not providing federated results.

**Comment by riasvdv** [comment]
The criteria is now just an `ElementQuery` object, so you could set `siteId` to '*' or specific IDs you want, you'll have to handle how you separate the content yourself in your transformer. Scout has no assumptions anymore here.

As for multilingual search, [Algolia suggests](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/how-to/multilingual-search/) to always use separate indices for those

**Comment by timkelty** [comment]
👏
