### ISSUE TITLE
Allow import in batches

### ISSUE THREAD

**Issue by lenvanessen** [riasvdv/craft-scout#58]
I have 5000 entry, currently it hits the memory limit and doesn't import all of them. Would be nice to have a feature to chuck them or another way around hitting the memory limit when having more posts!

**Comment by Rias500** [comment]
A solution when running in console can be to add the following `php -d memory_limit=512M craft scout/index/import`

**Comment by riasvdv** [comment]
Added in v2 (ready to test) https://github.com/riasvdv/craft-scout/tree/v2
