### ISSUE TITLE
Possible to sync two APIs?

### ISSUE THREAD

**Issue by JonnyBR12** [riasvdv/craft-scout#74]
Hey! I have two Algolia APIs that I'd like to sync content to. Is this something that you've done before? Reason being is that it's two accounts of products into one website. The search functions are completely separate but need to forward two different channels to two different Algolia APIs. 

Any help would be awesome!

**Comment by riasvdv** [comment]
This is currently not possible, I'd imagine we'd need the ability to override the keys at the mapping level, but it's not something I need.

I'd accept a PR that implements this though!
