### ISSUE TITLE
Bug when skipping elements when splitElementIndex is also set.

### ISSUE THREAD

**Issue by smaida** [riasvdv/craft-scout#81]
We're returning an empty array as noted in the docs. In cases where we do this and we also have splitElementIndex the following error occurs. 

`PHP Notice 'yii\base\ErrorException' with message 'Undefined index: body'
in vendor/rias/craft-scout/src/models/AlgoliaIndex.php:219`

**Comment by riasvdv** [comment]
Fixed in 1.3.1!
