### ISSUE TITLE
Items for multisite not being removed

### ISSUE THREAD

**Issue by dfrankes** [riasvdv/craft-scout#82]
We currently have a website up and running with 2 sites (for 2 different countries), When i create a new entry, for an example a page, it will create 2 items in Algolia (both with a different siteId) But when i remove the item, only the item with siteId 1 will be removed (in Algolia), not the other one. (If i change the storeView to the second domain, it will remove only the item for the  selected store, but craft will remove the item from both sites, not just one)

The data (Algolia hits array)
[hits.txt](https://github.com/riasvdv/craft-scout/files/3497259/hits.txt)

Kind Regards,

**Comment by riasvdv** [comment]
v2 should solve this, it's now ready for testing https://github.com/riasvdv/craft-scout/tree/v2 by requiring `dev-v2` in composer.json, please note the configuration has changed
