### ISSUE TITLE
Allow for eager loading in the `criteria` section of a map

### ISSUE THREAD

**Issue by aaronbushnell** [riasvdv/craft-scout#84]
Really great work on this plugin! 

I can't seem to get eager loading to work when I have my `scout.php` file setup like so:

```php
<?php

use craft\elements\Entry;

return [
    "sync" => true,
    "connect_timeout" => 1,
    "application_id" => getenv("ALGOLIA_APP_ID"),
    "admin_api_key" => getenv("ALGOLIA_API_KEY"),
    "mappings" => [
        [
            "indexName" => "my_index",
            "elementType" => Entry::class,
            "criteria" => [
                "section" => "test",
                "with" => [
                    "photo"
                ]
            ],
            "transformer" => function (Entry $entry) {
                Craft::dd($entry->photo); // Outputs an craft\elements\db\AssetQuery instead of array
            }
        ]
    ],
];
```

Not sure if I'm missing something on my end!

**Comment by riasvdv** [comment]
You'll need to use `$entry->photo->one()` or `$entry->photo->all()`, just like in your templates, I don't think the criteria support eager loading at this time in Scout

**Comment by riasvdv** [comment]
What you get passed in the transformer is actually the Entry that was saved, we don't do any eager loading on it, the criteria is just to check if it matches and it should index.

Eager loading also has no benefit if you're only operating on one element.

**Comment by aaronbushnell** [comment]
Ah, makes sense! Thanks for the explanation on this
