### ISSUE TITLE
Indexing/deindexing jobs are awkward with multiple indices/mappings

### ISSUE THREAD

**Issue by timkelty** [riasvdv/craft-scout#85]
From what I gather, here's what currently happens:

When an element is saved, Scout loops through every mapping, and indexes where it can, and de-indexes where it can't.

That means if I have 5 mappings, I end up with jobs like this:

- Indexing element 1_xxx
- Deindexing element 1_xxx
- Deindexing element 1_xxx
- Deindexing element 1_xxx
- Deindexing element 1_xxx

That seems problematic in terms of Algolia operations AND just in feedback to the user/dev. It seems like if saved element doesn't match a criteria, we should be able to bail earlier and not even run a job at all, and thus not incur pointless algolia operations.

**Comment by riasvdv** [comment]
I'll get this fixed in v2 ;)

**Comment by riasvdv** [comment]
Fixed in v2, as every Index (mapping) is now only for 1 site
