### ISSUE TITLE
Matrix block reset after query

### ISSUE THREAD

**Issue by ArtDepartmentMJ** [riasvdv/craft-scout#92]
Not sure if this is an issue with Craft or Scout however...

When pulling content from a matrix in the transform, querying the matrix will return the matrix in its original state. 

for example:

Matrix (handle: contentBlocks) with one block (handle: text) containing plain text field

Initial saved entry with two (contentBlocks) blocks of type text

When adding a new block of type text, saving and sending to Scout though the following transformer:
````
'transformer' => function (craft\base\Element $element) {
	$preQueryCount = count($element->contentBlocks);
	$allTextBlocks = $element->contentBlocks->type('text')->all();	
	$postQueryCount = count($element->contentBlocks);
	return [
		...
	];
}
````
$preQueryCount will be 3 however $postQueryCount will be 2 and $element->contentBlocks will now be the element in it's initial state.

I believe this has only started happening since Craft 3.2.

**Comment by riasvdv** [comment]
I've released 2.0.0! https://github.com/riasvdv/craft-scout/releases/tag/2.0.0 let me know how the upgrade goes
