### ISSUE TITLE
Creating Hierarchical Menu

### ISSUE THREAD

**Issue by pixelbeatcreative** [riasvdv/craft-scout#96]
In order for Algolia to be able to create a hierarchal Menu, is states that the json should look like below

`"categories.lvl0": ["products", "goods"],`
`"categories.lvl1": ["products > fruits", "goods > to eat"]`

I'm new to php and I was able to render any one category level but I don't know how to render the first and second level categories with the `>` in between them.  Can someone please help me with this? Everything else is working perfectly.

This is what I have right now:

`'categories.lvl0' => array_map('strval', $entry->locationCategories->level(1)->all()),`
`'categories.lvl1' => array_map('strval', $entry->locationCategories->level(2)->all()),`

**Comment by riasvdv** [comment]
I suggest asking on the [Craft Discord](https://craftcms.com/discord) or the [Craft Stackexchange](https://craftcms.stackexchange.com) on how to create this structure in PHP, it's not really related to Scout other than that it ends up in Algolia, the structure is just PHP.

When you find out how to do it, you can always link the solution here for other people!

**Comment by pixelbeatcreative** [comment]
I already asked on Discord before bring it here. I understand it may be related to php but it is needed for your plugin to function and I'm sure there will be others who may have this same issue as there's absolutely no reference or guidance on this in your docs. Wouldn't it be fair to leave this open for a while because maybe someone else will be able to help out?

**Comment by pixelbeatcreative** [comment]
I was able to find the answer and got it working. It can be found [here on stackexchange](https://craftcms.stackexchange.com/questions/30441/how-do-i-iterate-over-a-categories-field-in-an-entry) and the answer was provided by Fred Carlsen. I pasted the snippet below as well for anyone who may need it.

`<?php
return [
    'transformer' => function(craft\base\Element $entry) {
        $level1Categories = [];
        $level2Categories = [];
        $level3Categories = [];

        foreach ($entry->categoryFieldName->level(1)->all() as $category) {
            /** @var $category \craft\elements\Category */
            $level1Categories[] = $category->title;
            $children = $category->getChildren()->level(2)->all();

            foreach ($children as $child) {
                /** @var $child \craft\elements\Category */
                $crumb = [
                    $category->title,
                    $child->title,
                ];

                $level2Categories[] = implode(' > ', $crumb);

                foreach ($child->getChildren()->level(3)->all() as $subChild) {
                    /** @var $subChild \craft\elements\Category */
                    $crumb = [
                        $category->title,
                        $child->title,
                        $subChild->title
                    ];

                    $level3Categories[] = implode(' > ', $crumb);
                }
            }
        }

        return [
            'categories.lvl0' => $level1Categories,
            'categories.lvl1' => $level2Categories,
            'categories.lvl2' => $level3Categories,

            ],
        ];
    },
];`

**Comment by riasvdv** [comment]
Thanks for your research!
